"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras_hub.src.distribution.auto_model_parallel import (
    AutoModelParallel as AutoModelParallel,
)
